//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Languages.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount *.
        /// </summary>
        public static string Cantitate {
            get {
                return ResourceManager.GetString("Cantitate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight *.
        /// </summary>
        public static string Gramaj {
            get {
                return ResourceManager.GetString("Gramaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nr. of Menus *.
        /// </summary>
        public static string Nrmeniuri {
            get {
                return ResourceManager.GetString("Nrmeniuri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number *.
        /// </summary>
        public static string Nrtel {
            get {
                return ResourceManager.GetString("Nrtel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name *.
        /// </summary>
        public static string Nume {
            get {
                return ResourceManager.GetString("Nume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu *.
        /// </summary>
        public static string NumeMeniu {
            get {
                return ResourceManager.GetString("NumeMeniu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password *.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price *.
        /// </summary>
        public static string Pret {
            get {
                return ResourceManager.GetString("Pret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit *.
        /// </summary>
        public static string Unitate_masura {
            get {
                return ResourceManager.GetString("Unitate_masura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username *.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
    }
}
